name: Node.js Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Verificar a formatação do código
        run: npm run format:check && echo "Código devidamente formatado"

      - name: Verificar inicialização do servidor (simples)
        run: |
          timeout 5s npm start || echo "Servidor iniciado (verificação superficial)"
